linters:
  enable:
  - exhaustive
  - goconst
  - err113
  - gofmt
  - gofumpt
  - goimports
  - revive
  - goprintffuncname
  - gosec
  - misspell
  - whitespace
severity:
  default-severity: blocker
linters-settings:
  goimports:
    local-prefixes: github.com/tmobile/depaginator
